### ISSUE TITLE
Published package is broken

### ISSUE THREAD

**Issue by guimard** [NMinhNguyen/react-shallow-renderer#96]
Hi,

`npm i react-shallow-renderer` does not install required files

**Comment by NMinhNguyen** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by guimard** [comment]
Hi @NMinhNguyen,

simply launch `npm i react-shallow-renderer && node -e 'require("react-shallow-renderer")'` in an empty directory

**Comment by NMinhNguyen** [comment]
`react-shallow-renderer` has a [peer dependency](https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies) on `react` meaning you have to have it installed: https://github.com/NMinhNguyen/react-shallow-renderer/blob/5c131d826815bc1b3afff568732d2363c090c588/package.json#L54-L56

**Comment by guimard** [comment]
```
$ ls -l node_modules/react-shallow-renderer/
total 16
-rw-r--r-- 1 xavier xavier  254 26 oct.   1985 index.js
-rw-r--r-- 1 xavier xavier 1086 26 oct.   1985 LICENSE
-rw-r--r-- 1 xavier xavier 3181 21 oct.  12:50 package.json
-rw-r--r-- 1 xavier xavier 2446 26 oct.   1985 README.md
$ cat node_modules/react-shallow-renderer/index.js 
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 */

export {default} from './src/ReactShallowRenderer';
```

`src` directory is missing

**Comment by guimard** [comment]
So I'm unable to reproduce react build

**Comment by NMinhNguyen** [comment]
I'll publish a new version shortly

**Comment by guimard** [comment]
Thanks
